### ISSUE TITLE
Css Style support

### ISSUE THREAD

**Issue by micheilsgrey** [meliorence/react-native-render-html#445]
Hello i have css style for my html. I am trying to convert it to react style and not everything getting my new custom style. 

Code: 

```typescript 
 classesStyles={{
                'news-content': {
                  backgroundColor: '#0C2B33',
                  fontSize: 16,
                  color: '#fff',
                  lineHeight: 18,
                  paddingTop: 8,
                  paddingLeft: 10,
                  paddingRight: 10,
                  paddingBottom: 10,
                },
                hentry: {
                  backgroundColor: '#07232B',
                  paddingTop: 5,
                  paddingBottom: 5,
                },
                'news-title': {
                  fontFamily: 'BeaufortBold',
                  fontSize: 20,
                  fontWeight: '400',
                  color: '#B8B46C',
                  textTransform: 'uppercase',
                  marginTop: 5,
                  marginLeft: 10,
                  marginRight: 10,
                  marginBottom: 0,
                  lineHeight: 20,
                },
                'news-date': {
                  fontFamily: 'ProximaNova-Regular',
                  fontSize: 16,
                  fontWeight: '400',
                  color: '#D6FFFD',
                  marginTop: -2,
                  marginLeft: 10,
                  marginRight: 10,
                  marginBottom: 5,
                  display: 'flex',
                },
                'news-date a': { //not working
                  color: 'black',
                  //fontWeight: '400',
                },
                'news-content a': { //not working
                  color: '#D6FFFD',
                },
                'news-content h2': { //not working
                  fontSize: 50,
                },
                'news-content h3': { //not working
                  fontSize: 20,
                  color: '#6AFCFA',
                },
                'separator b a': { //not working
                  color: '#6AFCFA',
                },
              }}
```

this is my css: 

```css
.hentry{
    background-color: #07232B;
    margin-top: 10px;
    color: #fff;
    padding-top: 5px;
    padding-bottom: 5px;
}
.news-title{
    font-family: 'Montserrat',sans-serif;
    font-size: 20px;
    font-weight: 700;
    color: #B8B46C!important;
    text-transform: uppercase;
    margin: 5px 10px 0;
    line-height: 20px;
}
.news-date{
    font-family: 'Montserrat',sans-serif;
    font-size: 16px;
    font-weight: 400;
    color: #D6FFFD;
    margin: -2px 10px 5px;
    display: block;
}
.news-date a{
    color: #D6FFFD!important;
    text-decoration: none!important;
    font-weight: 700;
}
.news-content{
    background: #0C2B33;
    font-size: 16px;
    color: #fff;
    line-height: 18px;
    background-image: url(https://1.bp.blogspot.com/-yYGqqM0TFEA/UO7HLXDA5bI/AAAAAAAAAic/NXIFxqaaW78/s1600/news-gradient.png);
    background-repeat: repeat-x;
    padding: 8px 10px 10px;
}
.news-content a{
    color: #D6FFFD!important;
}
.news-content h2{
    font-size: 18px;
}
.news-content h3{
    font-size: 20px;
    color: #6AFCFA;
}
.separator b a{
    color: #6AFCFA;
}


```

So everything working fine but styles like '.separator b a' or  '.news-content a' not working. What should I do to make those styles work?
